/** 用户管理子模块：页面文案与演示数据（对接真实 API 时替换 rows 数据源即可） */
export type UserModuleKey =
  | 'agents'
  | 'referrals'
  | 'kycBasic'
  | 'kycC2c'
  | 'kycAdvanced'
  | 'manualReset'
  | 'basicProfiles'
  | 'list'
  | 'contacts'

export interface UserModuleStat {
  label: string
  value: string
  tone?: 'default' | 'warn' | 'ok' | 'muted'
}

export interface UserModuleColumn {
  prop: string
  label: string
  width?: number
  minWidth?: number
  display?: 'text' | 'date' | 'tag'
  tagMap?: Record<string, { type: 'success' | 'warning' | 'info' | 'danger'; label: string }>
  /** 地址/哈希等用等宽展示 */
  mono?: boolean
  /** 默认参与列头排序；设为 false 可关闭（如纯操作类衍生列） */
  sortable?: boolean
}

export interface UserModuleDef {
  title: string
  subtitle: string
  hint?: string
  stats?: UserModuleStat[]
  columns: UserModuleColumn[]
  rows: Record<string, unknown>[]
  /** 筛选栏关键词框占位 */
  keywordPlaceholder?: string
  /** 筛选栏「关键词」表单项标签 */
  filterKeywordLabel?: string
  /** 工具栏列表标题（默认「{title} · 列表」） */
  listCaption?: string
  /** 详情抽屉底部说明（覆盖通用文案） */
  drawerNote?: string
}

const df = (ts: number) => new Date(ts).toLocaleString('zh-CN')

const TIER_MAP = {
  L1: { type: 'warning' as const, label: '一级' },
  L2: { type: 'info' as const, label: '二级' },
  L3: { type: 'success' as const, label: '三级' },
}

const REBATE_MAP = {
  ACTIVE: { type: 'success' as const, label: '生效' },
  PENDING: { type: 'warning' as const, label: '待生效' },
  FROZEN: { type: 'danger' as const, label: '冻结' },
}

const KYC_BASIC_STATUS = {
  PENDING: { type: 'warning' as const, label: '待审核' },
  APPROVED: { type: 'success' as const, label: '已通过' },
  REJECTED: { type: 'danger' as const, label: '已驳回' },
}

const KYC_C2C_STATUS = {
  REVIEW: { type: 'warning' as const, label: '审核中' },
  OK: { type: 'success' as const, label: '已认证' },
  REJECT: { type: 'danger' as const, label: '未通过' },
}

const KYC_ADV_STATUS = {
  PENDING: { type: 'warning' as const, label: '待审' },
  REVIEW: { type: 'info' as const, label: '尽调中' },
  DONE: { type: 'success' as const, label: '完成' },
  REJECT: { type: 'danger' as const, label: '驳回' },
}

const TICKET_STATUS = {
  OPEN: { type: 'danger' as const, label: '处理中' },
  WAIT_USER: { type: 'warning' as const, label: '待用户' },
  DONE: { type: 'success' as const, label: '已关闭' },
}

const RISK_MAP = {
  NORMAL: { type: 'info' as const, label: '正常' },
  WATCH: { type: 'warning' as const, label: '观察' },
  HIGH: { type: 'danger' as const, label: '高危' },
}

const ACCT_MAP = {
  ON: { type: 'success' as const, label: '正常' },
  LOCK: { type: 'danger' as const, label: '冻结' },
  LIMIT: { type: 'warning' as const, label: '限制' },
}

const USER_KYC_MAP = {
  '0': { type: 'info' as const, label: '未认证' },
  '1': { type: 'success' as const, label: '基础' },
  '2': { type: 'success' as const, label: '高级' },
}

const USER_STATUS_MAP = {
  OK: { type: 'success' as const, label: '正常' },
  BAN: { type: 'danger' as const, label: '封禁' },
  SLEEP: { type: 'info' as const, label: '休眠' },
}

const VERIFIED_MAP = {
  '1': { type: 'success' as const, label: '已验' },
  '0': { type: 'warning' as const, label: '未验' },
}

export const ADMIN_USER_MODULE_REGISTRY: Record<UserModuleKey, UserModuleDef> = {
  agents: {
    title: '代理商',
    subtitle:
      '维护机构与渠道代理的签约层级、分润比例、区域与合约周期；支持续约提醒与下级用户规模透视。对接示例：GET /v1/admin/users/agents。',
    hint: '原型 · 机构 / 区域',
    keywordPlaceholder: '代理编码 / 名称 / 联系人',
    filterKeywordLabel: '检索',
    listCaption: '代理商目录',
    drawerNote: '生产环境可挂载合同扫描件、结算账户、历史分润曲线与合规尽调材料。',
    stats: [
      { label: '一级代理', value: '12', tone: 'default' },
      { label: '待续约', value: '3', tone: 'warn' },
      { label: '本月新增', value: '2', tone: 'ok' },
      { label: '下级用户(估)', value: '42.1万', tone: 'muted' },
    ],
    columns: [
      { prop: 'code', label: '代理编码', width: 118 },
      { prop: 'name', label: '名称', minWidth: 140 },
      { prop: 'tier', label: '等级', width: 88, display: 'tag', tagMap: TIER_MAP },
      { prop: 'commission', label: '分润(%)', width: 88 },
      { prop: 'region', label: '区域', width: 100 },
      { prop: 'contact', label: '对接人', minWidth: 100 },
      { prop: 'userCount', label: '下级用户', width: 100 },
      { prop: 'contractEnd', label: '合约到期', width: 118, display: 'date' },
      { prop: 'updatedAt', label: '最近更新', minWidth: 160, display: 'date' },
    ],
    rows: [
      {
        code: 'AG-1001',
        name: '华东运营中心',
        tier: 'L1',
        commission: '35',
        region: '华东',
        contact: '周*',
        userCount: '128,400',
        contractEnd: df(Date.now() + 86400000 * 40),
        updatedAt: df(Date.now() - 86400000),
      },
      {
        code: 'AG-2044',
        name: '星辰渠道',
        tier: 'L2',
        commission: '22',
        region: '华南',
        contact: '陈*',
        userCount: '56,200',
        contractEnd: df(Date.now() + 86400000 * 180),
        updatedAt: df(Date.now() - 3600000),
      },
      {
        code: 'AG-3102',
        name: '海外机构 A',
        tier: 'L1',
        commission: '30',
        region: '东南亚',
        contact: 'Lee*',
        userCount: '89,000',
        contractEnd: df(Date.now() - 86400000 * 5),
        updatedAt: df(Date.now() - 7200000),
      },
      {
        code: 'AG-0891',
        name: '社区 KOL 联盟',
        tier: 'L3',
        commission: '18',
        region: '全国',
        contact: '赵*',
        userCount: '12,800',
        contractEnd: df(Date.now() + 86400000 * 90),
        updatedAt: df(Date.now() - 172800000),
      },
      {
        code: 'AG-4450',
        name: '华北企服',
        tier: 'L2',
        commission: '25',
        region: '华北',
        contact: '钱*',
        userCount: '33,100',
        contractEnd: df(Date.now() + 86400000 * 12),
        updatedAt: df(Date.now() - 259200000),
      },
      {
        code: 'AG-5011',
        name: '量化团队渠道',
        tier: 'L2',
        commission: '20',
        region: '华东',
        contact: '孙*',
        userCount: '8,420',
        contractEnd: df(Date.now() + 86400000 * 200),
        updatedAt: df(Date.now() - 432000000),
      },
      {
        code: 'AG-2208',
        name: '西南商户拓展',
        tier: 'L3',
        commission: '15',
        region: '西南',
        contact: '吴*',
        userCount: '21,300',
        contractEnd: df(Date.now() + 86400000 * 60),
        updatedAt: df(Date.now() - 518400000),
      },
      {
        code: 'AG-9901',
        name: '机构直销（内渠）',
        tier: 'L1',
        commission: '40',
        region: '总部',
        contact: '内渠组',
        userCount: '201,000',
        contractEnd: df(Date.now() + 86400000 * 300),
        updatedAt: df(Date.now() - 600000),
      },
    ],
  },
  referrals: {
    title: '推荐关系',
    subtitle:
      '邀请人与被邀请人绑定链路、返佣生效与冻结状态；可追溯到活动批次与渠道码。对接示例：GET /v1/admin/users/referrals。',
    keywordPlaceholder: '邀请人 / 被邀请人 UID / 活动码',
    filterKeywordLabel: '检索',
    listCaption: '推荐关系明细',
    drawerNote: '可扩展展示：邀请层级图、首笔入金时间、返佣结算周期与争议仲裁记录。',
    stats: [
      { label: '有效关系', value: '8,420', tone: 'ok' },
      { label: '待复核', value: '14', tone: 'warn' },
      { label: '本月新增绑定', value: '326', tone: 'default' },
      { label: '冻结返佣', value: '7', tone: 'muted' },
    ],
    columns: [
      { prop: 'inviter', label: '邀请人 UID', width: 120 },
      { prop: 'invitee', label: '被邀请人 UID', width: 120 },
      { prop: 'level', label: '层级', width: 72 },
      { prop: 'campaign', label: '活动/渠道', minWidth: 120 },
      { prop: 'rebateStatus', label: '返佣状态', width: 100, display: 'tag', tagMap: REBATE_MAP },
      { prop: 'firstDeposit', label: '首入金', width: 118, display: 'date' },
      { prop: 'bindAt', label: '绑定时间', minWidth: 160, display: 'date' },
    ],
    rows: [
      {
        inviter: 'U883021',
        invitee: 'U991204',
        level: '1',
        campaign: '2026-Q1 拉新',
        rebateStatus: 'ACTIVE',
        firstDeposit: df(Date.now() - 86400000 * 20),
        bindAt: df(Date.now() - 172800000),
      },
      {
        inviter: 'A100001',
        invitee: 'U440012',
        level: '1',
        campaign: '代理专属码 AG-1001',
        rebateStatus: 'PENDING',
        firstDeposit: df(Date.now() - 3600000),
        bindAt: df(Date.now() - 7200000),
      },
      {
        inviter: 'U440012',
        invitee: 'U550901',
        level: '2',
        campaign: '二级裂变',
        rebateStatus: 'ACTIVE',
        firstDeposit: df(Date.now() - 86400000 * 3),
        bindAt: df(Date.now() - 86400000 * 5),
      },
      {
        inviter: 'U204881',
        invitee: 'U661102',
        level: '1',
        campaign: '站内 H5',
        rebateStatus: 'FROZEN',
        firstDeposit: df(Date.now() - 86400000 * 90),
        bindAt: df(Date.now() - 86400000 * 100),
      },
      {
        inviter: 'U778899',
        invitee: 'U778900',
        level: '1',
        campaign: '老带新双倍',
        rebateStatus: 'PENDING',
        firstDeposit: df(Date.now() - 600000),
        bindAt: df(Date.now() - 1800000),
      },
      {
        inviter: 'U332211',
        invitee: 'U332888',
        level: '1',
        campaign: 'APP 分享',
        rebateStatus: 'ACTIVE',
        firstDeposit: df(Date.now() - 86400000),
        bindAt: df(Date.now() - 86400000 * 2),
      },
      {
        inviter: 'AG-2044',
        invitee: 'U900771',
        level: '1',
        campaign: '渠道星辰',
        rebateStatus: 'ACTIVE',
        firstDeposit: df(Date.now() - 86400000 * 45),
        bindAt: df(Date.now() - 86400000 * 50),
      },
      {
        inviter: 'U100001',
        invitee: 'U100888',
        level: '1',
        campaign: '默认邀请',
        rebateStatus: 'PENDING',
        firstDeposit: df(Date.now() - 120000),
        bindAt: df(Date.now() - 3600000),
      },
    ],
  },
  kycBasic: {
    title: '用户基础认证',
    subtitle:
      '身份证件、人脸比对、活体检测结果与公安库核验状态；队列按风险分与等待时长排序。对接示例：GET /v1/admin/users/kyc/basic。',
    hint: '侧栏角标为待审演示',
    keywordPlaceholder: '用户码 / 姓名 / 证件尾号',
    filterKeywordLabel: '检索',
    listCaption: '基础 KYC 审核队列',
    drawerNote: '生产环境展示证件缩略图、活体分数、重复证件命中、审核人与操作日志（不可篡改）。',
    stats: [
      { label: '待审核', value: '3', tone: 'warn' },
      { label: '今日通过', value: '56', tone: 'ok' },
      { label: '今日驳回', value: '4', tone: 'muted' },
      { label: '平均等待', value: '42 分', tone: 'default' },
    ],
    columns: [
      { prop: 'userCode', label: '用户', width: 112 },
      { prop: 'realName', label: '姓名', minWidth: 96 },
      { prop: 'idType', label: '证件类型', width: 100 },
      { prop: 'idTail', label: '证件尾号', width: 96 },
      { prop: 'country', label: '国家/地区', width: 110 },
      { prop: 'riskScore', label: '模型分', width: 80 },
      { prop: 'status', label: '状态', width: 100, display: 'tag', tagMap: KYC_BASIC_STATUS },
      { prop: 'submittedAt', label: '提交时间', minWidth: 160, display: 'date' },
    ],
    rows: [
      {
        userCode: 'U440102',
        realName: '张**',
        idType: '身份证',
        idTail: '***1023',
        country: '中国',
        riskScore: '18',
        status: 'PENDING',
        submittedAt: df(Date.now() - 5400000),
      },
      {
        userCode: 'U440103',
        realName: '李**',
        idType: '身份证',
        idTail: '***8891',
        country: '中国',
        riskScore: '22',
        status: 'PENDING',
        submittedAt: df(Date.now() - 1800000),
      },
      {
        userCode: 'U440105',
        realName: '王**',
        idType: '护照',
        idTail: '**771',
        country: '新加坡',
        riskScore: '35',
        status: 'PENDING',
        submittedAt: df(Date.now() - 600000),
      },
      {
        userCode: 'U440108',
        realName: '刘**',
        idType: '身份证',
        idTail: '***2201',
        country: '中国',
        riskScore: '12',
        status: 'APPROVED',
        submittedAt: df(Date.now() - 86400000),
      },
      {
        userCode: 'U440110',
        realName: '陈**',
        idType: '身份证',
        idTail: '***5560',
        country: '中国',
        riskScore: '48',
        status: 'REJECTED',
        submittedAt: df(Date.now() - 86400000 * 2),
      },
      {
        userCode: 'U440120',
        realName: '赵**',
        idType: '身份证',
        idTail: '***0098',
        country: '中国',
        riskScore: '15',
        status: 'APPROVED',
        submittedAt: df(Date.now() - 86400000 * 3),
      },
      {
        userCode: 'U440130',
        realName: '周**',
        idType: '港澳通行证',
        idTail: '**12',
        country: '中国',
        riskScore: '28',
        status: 'PENDING',
        submittedAt: df(Date.now() - 900000),
      },
      {
        userCode: 'U440140',
        realName: '吴**',
        idType: '身份证',
        idTail: '***3344',
        country: '中国',
        riskScore: '9',
        status: 'APPROVED',
        submittedAt: df(Date.now() - 86400000 * 5),
      },
    ],
  },
  kycC2c: {
    title: '用户 C2C 认证',
    subtitle:
      '承兑商/广告主的实人增补、店铺资质、收付款账户与白名单校验；与 C2C 风控策略联动。对接示例：GET /v1/admin/users/kyc/c2c。',
    keywordPlaceholder: '用户 / 店铺名',
    filterKeywordLabel: '检索',
    listCaption: 'C2C 商家认证',
    drawerNote: '可挂载店铺证照、法人与受益人信息、历史纠纷单与保证金状态。',
    stats: [
      { label: '审核中', value: '5', tone: 'warn' },
      { label: '已认证商家', value: '1,024', tone: 'ok' },
      { label: '近 7 日新增', value: '18', tone: 'default' },
      { label: '高风险店铺', value: '2', tone: 'muted' },
    ],
    columns: [
      { prop: 'userCode', label: '用户', width: 112 },
      { prop: 'shopName', label: '店铺/备注', minWidth: 140 },
      { prop: 'adsCount', label: '在挂广告', width: 96 },
      { prop: 'margin', label: '保证金', width: 100 },
      { prop: 'riskScore', label: '风险分', width: 80 },
      { prop: 'status', label: '状态', width: 100, display: 'tag', tagMap: KYC_C2C_STATUS },
      { prop: 'updatedAt', label: '更新', minWidth: 160, display: 'date' },
    ],
    rows: [
      {
        userCode: 'U221008',
        shopName: '极速换汇',
        adsCount: '6',
        margin: '5,000 USDT',
        riskScore: '12',
        status: 'REVIEW',
        updatedAt: df(Date.now() - 86400000),
      },
      {
        userCode: 'U221015',
        shopName: '安心 OTC',
        adsCount: '3',
        margin: '12,000 USDT',
        riskScore: '8',
        status: 'OK',
        updatedAt: df(Date.now() - 3600000),
      },
      {
        userCode: 'U221022',
        shopName: '24H 承兑',
        adsCount: '0',
        margin: '8,000 USDT',
        riskScore: '44',
        status: 'REVIEW',
        updatedAt: df(Date.now() - 7200000),
      },
      {
        userCode: 'U221030',
        shopName: '小额快兑',
        adsCount: '12',
        margin: '3,000 USDT',
        riskScore: '55',
        status: 'REJECT',
        updatedAt: df(Date.now() - 86400000 * 4),
      },
      {
        userCode: 'U221040',
        shopName: '机构场外',
        adsCount: '2',
        margin: '50,000 USDT',
        riskScore: '15',
        status: 'OK',
        updatedAt: df(Date.now() - 86400000 * 10),
      },
      {
        userCode: 'U221055',
        shopName: '新店（试运营）',
        adsCount: '1',
        margin: '2,000 USDT',
        riskScore: '30',
        status: 'REVIEW',
        updatedAt: df(Date.now() - 1800000),
      },
      {
        userCode: 'U221060',
        shopName: '华南承兑',
        adsCount: '8',
        margin: '15,000 USDT',
        riskScore: '20',
        status: 'OK',
        updatedAt: df(Date.now() - 86400000 * 2),
      },
    ],
  },
  kycAdvanced: {
    title: '用户高级认证',
    subtitle:
      '大额、机构与合规加强认证；包含尽调材料、额度申请与审批链。对接示例：GET /v1/admin/users/kyc/advanced。',
    keywordPlaceholder: '用户 / 企业名称',
    filterKeywordLabel: '检索',
    listCaption: '高级认证工单',
    drawerNote: '可展示公司章程、UBO 表、银行资信、链上地址证明与多级审批意见。',
    stats: [
      { label: '待初审', value: '4', tone: 'warn' },
      { label: '尽调中', value: '2', tone: 'default' },
      { label: '已通过(本月)', value: '11', tone: 'ok' },
      { label: '累计额度池', value: '2.4 亿 U', tone: 'muted' },
    ],
    columns: [
      { prop: 'userCode', label: '用户', width: 112 },
      { prop: 'entity', label: '主体类型', width: 100 },
      { prop: 'entityName', label: '主体名称', minWidth: 140 },
      { prop: 'limitReq', label: '申请额度', minWidth: 120 },
      { prop: 'assignee', label: '当前处理人', width: 110 },
      { prop: 'status', label: '状态', width: 100, display: 'tag', tagMap: KYC_ADV_STATUS },
      { prop: 'submittedAt', label: '提交', minWidth: 160, display: 'date' },
    ],
    rows: [
      {
        userCode: 'U900001',
        entity: '企业',
        entityName: '某科技 ***',
        limitReq: '500W USDT/日',
        assignee: '合规 A 组',
        status: 'PENDING',
        submittedAt: df(Date.now() - 259200000),
      },
      {
        userCode: 'U900012',
        entity: '企业',
        entityName: '跨境贸易 ***',
        limitReq: '200W USDT/日',
        assignee: '合规 B 组',
        status: 'REVIEW',
        submittedAt: df(Date.now() - 86400000 * 4),
      },
      {
        userCode: 'U900088',
        entity: '个人',
        entityName: '高净值个人',
        limitReq: '100W USDT/日',
        assignee: '—',
        status: 'PENDING',
        submittedAt: df(Date.now() - 43200000),
      },
      {
        userCode: 'U900100',
        entity: '企业',
        entityName: '基金 ***',
        limitReq: '1000W USDT/日',
        assignee: '法务复核',
        status: 'REVIEW',
        submittedAt: df(Date.now() - 86400000 * 12),
      },
      {
        userCode: 'U900200',
        entity: '企业',
        entityName: '矿机托管 ***',
        limitReq: '80W USDT/日',
        assignee: '—',
        status: 'DONE',
        submittedAt: df(Date.now() - 86400000 * 30),
      },
      {
        userCode: 'U900210',
        entity: '个人',
        entityName: '机构交易员',
        limitReq: '50W USDT/日',
        assignee: '—',
        status: 'REJECT',
        submittedAt: df(Date.now() - 86400000 * 45),
      },
    ],
  },
  manualReset: {
    title: '人工重置管理',
    subtitle:
      '登录保护、资金密码、2FA、手机/邮箱换绑等人工工单；需双人复核与留痕。对接示例：GET /v1/admin/users/resets。',
    keywordPlaceholder: '工单号 / 用户 / 类型',
    filterKeywordLabel: '检索',
    listCaption: '人工重置工单',
    drawerNote: '展示用户举证材料、历史设备指纹、客服沟通摘要与关闭原因码。',
    stats: [
      { label: '开放工单', value: '5', tone: 'warn' },
      { label: '待用户补充', value: '2', tone: 'default' },
      { label: '今日关闭', value: '17', tone: 'ok' },
      { label: 'SLA 超时', value: '1', tone: 'muted' },
    ],
    columns: [
      { prop: 'ticketId', label: '工单号', width: 148 },
      { prop: 'userCode', label: '用户', width: 112 },
      { prop: 'type', label: '类型', minWidth: 120 },
      { prop: 'channel', label: '来源', width: 88 },
      { prop: 'priority', label: '优先级', width: 88, display: 'tag', tagMap: { P1: { type: 'danger', label: 'P1' }, P2: { type: 'warning', label: 'P2' }, P3: { type: 'info', label: 'P3' } } },
      { prop: 'status', label: '状态', width: 110, display: 'tag', tagMap: TICKET_STATUS },
      { prop: 'createdAt', label: '创建', minWidth: 160, display: 'date' },
    ],
    rows: [
      {
        ticketId: 'RST-20260401001',
        userCode: 'U332211',
        type: '资金密码重置',
        channel: '工单',
        priority: 'P1',
        status: 'OPEN',
        createdAt: df(Date.now() - 14400000),
      },
      {
        ticketId: 'RST-20260401008',
        userCode: 'U440102',
        type: '手机换绑复核',
        channel: '在线客服',
        priority: 'P2',
        status: 'WAIT_USER',
        createdAt: df(Date.now() - 7200000),
      },
      {
        ticketId: 'RST-20260330088',
        userCode: 'U778899',
        type: '谷歌验证解绑',
        channel: '邮件',
        priority: 'P2',
        status: 'DONE',
        createdAt: df(Date.now() - 432000000),
      },
      {
        ticketId: 'RST-20260330102',
        userCode: 'U551002',
        type: '登录保护解除',
        channel: '工单',
        priority: 'P3',
        status: 'OPEN',
        createdAt: df(Date.now() - 3600000),
      },
      {
        ticketId: 'RST-20260329155',
        userCode: 'U204881',
        type: '邮箱换绑',
        channel: 'APP',
        priority: 'P2',
        status: 'DONE',
        createdAt: df(Date.now() - 86400000 * 5),
      },
      {
        ticketId: 'RST-20260328001',
        userCode: 'U900001',
        type: 'API Key 紧急吊销',
        channel: '安全中心',
        priority: 'P1',
        status: 'DONE',
        createdAt: df(Date.now() - 86400000 * 8),
      },
      {
        ticketId: 'RST-20260327077',
        userCode: 'U100002',
        type: '人脸失败次数清零',
        channel: '工单',
        priority: 'P3',
        status: 'WAIT_USER',
        createdAt: df(Date.now() - 86400000 * 2),
      },
      {
        ticketId: 'RST-20260326033',
        userCode: 'U221008',
        type: '资金密码 + 2FA 联合重置',
        channel: '在线客服',
        priority: 'P1',
        status: 'OPEN',
        createdAt: df(Date.now() - 900000),
      },
    ],
  },
  basicProfiles: {
    title: '用户基础管理',
    subtitle:
      '账号资料、联系方式脱敏、风险标签与限制策略的底层维护；变更需审计。对接示例：GET /v1/admin/users/profiles。',
    keywordPlaceholder: 'UID / 邮箱 / 手机尾号',
    filterKeywordLabel: '检索',
    listCaption: '用户基础档案',
    drawerNote: '可联动展示设备列表、登录地热力、关联子账号与内部备注（权限分级可见）。',
    stats: [
      { label: '正常', value: '126,402', tone: 'ok' },
      { label: '冻结', value: '48', tone: 'warn' },
      { label: '限制交易', value: '112', tone: 'default' },
      { label: '观察名单', value: '326', tone: 'muted' },
    ],
    columns: [
      { prop: 'userCode', label: 'UID', width: 120 },
      { prop: 'email', label: '邮箱(脱敏)', minWidth: 180 },
      { prop: 'phone', label: '手机(脱敏)', width: 124 },
      { prop: 'region', label: '注册地', width: 100 },
      { prop: 'riskTag', label: '标签', width: 88, display: 'tag', tagMap: RISK_MAP },
      { prop: 'status', label: '账号', width: 88, display: 'tag', tagMap: ACCT_MAP },
      { prop: 'updatedAt', label: '更新', minWidth: 160, display: 'date' },
    ],
    rows: [
      {
        userCode: 'U100001',
        email: 'a***@example.com',
        phone: '138****8001',
        region: '中国',
        riskTag: 'NORMAL',
        status: 'ON',
        updatedAt: df(Date.now() - 3600000),
      },
      {
        userCode: 'U100002',
        email: 'b***@qq.com',
        phone: '159****2200',
        region: '中国',
        riskTag: 'WATCH',
        status: 'ON',
        updatedAt: df(Date.now() - 7200000),
      },
      {
        userCode: 'U100003',
        email: 'c***@gmail.com',
        phone: '—',
        region: '美国',
        riskTag: 'HIGH',
        status: 'LOCK',
        updatedAt: df(Date.now() - 86400000),
      },
      {
        userCode: 'U100004',
        email: 'd***@outlook.com',
        phone: '186****9012',
        region: '中国',
        riskTag: 'NORMAL',
        status: 'LIMIT',
        updatedAt: df(Date.now() - 120000),
      },
      {
        userCode: 'U100005',
        email: 'e***@163.com',
        phone: '177****3344',
        region: '中国',
        riskTag: 'WATCH',
        status: 'ON',
        updatedAt: df(Date.now() - 86400000 * 3),
      },
      {
        userCode: 'U100006',
        email: 'f***@proton.me',
        phone: '—',
        region: '德国',
        riskTag: 'NORMAL',
        status: 'ON',
        updatedAt: df(Date.now() - 86400000 * 6),
      },
      {
        userCode: 'U100007',
        email: 'g***@yahoo.com',
        phone: '199****7788',
        region: '中国',
        riskTag: 'NORMAL',
        status: 'ON',
        updatedAt: df(Date.now() - 600000),
      },
      {
        userCode: 'U100008',
        email: 'h***@foxmail.com',
        phone: '136****5566',
        region: '中国',
        riskTag: 'HIGH',
        status: 'LIMIT',
        updatedAt: df(Date.now() - 86400000 * 2),
      },
    ],
  },
  list: {
    title: '用户管理',
    subtitle:
      '全站用户检索、封禁/解封、内部备注与分群导出；与风控、客服、财务模块交叉引用。对接示例：GET /v1/admin/users。',
    keywordPlaceholder: 'UID / 昵称 / 手机 / 邮箱',
    filterKeywordLabel: '检索',
    listCaption: '用户检索结果',
    drawerNote: '详情可聚合：资产概览、订单摘要、KYC 状态、登录设备与操作日志时间线。',
    stats: [
      { label: '注册用户', value: '128,490', tone: 'default' },
      { label: '今日新增', value: '+312', tone: 'ok' },
      { label: '冻结', value: '48', tone: 'warn' },
      { label: '在线(估)', value: '1,204', tone: 'muted' },
    ],
    columns: [
      { prop: 'userCode', label: 'UID', width: 120 },
      { prop: 'nickname', label: '昵称', minWidth: 120 },
      { prop: 'phone', label: '手机(脱敏)', width: 124 },
      { prop: 'registerAt', label: '注册时间', width: 158, display: 'date' },
      { prop: 'vip', label: 'VIP', width: 72 },
      { prop: 'kyc', label: 'KYC', width: 88, display: 'tag', tagMap: USER_KYC_MAP },
      { prop: 'lastLogin', label: '最近登录', minWidth: 160, display: 'date' },
      { prop: 'lastIp', label: '最近 IP', width: 132, mono: true },
      { prop: 'status', label: '状态', width: 88, display: 'tag', tagMap: USER_STATUS_MAP },
    ],
    rows: [
      {
        userCode: 'U204881',
        nickname: 'North',
        phone: '138****1024',
        registerAt: df(Date.now() - 86400000 * 400),
        vip: '1',
        kyc: '1',
        lastLogin: df(Date.now() - 120000),
        lastIp: '183.60.*.*',
        status: 'OK',
      },
      {
        userCode: 'U204882',
        nickname: 'River',
        phone: '—',
        registerAt: df(Date.now() - 86400000 * 120),
        vip: '0',
        kyc: '0',
        lastLogin: df(Date.now() - 86400000),
        lastIp: '104.28.*.*',
        status: 'OK',
      },
      {
        userCode: 'U204883',
        nickname: '—',
        phone: '159****7781',
        registerAt: df(Date.now() - 86400000 * 30),
        vip: '2',
        kyc: '2',
        lastLogin: df(Date.now() - 10000),
        lastIp: '45.12.*.*',
        status: 'BAN',
      },
      {
        userCode: 'U204884',
        nickname: '量化_阿乐',
        phone: '186****0099',
        registerAt: df(Date.now() - 86400000 * 900),
        vip: '3',
        kyc: '2',
        lastLogin: df(Date.now() - 300000),
        lastIp: '58.220.*.*',
        status: 'OK',
      },
      {
        userCode: 'U204885',
        nickname: 'Sleepy',
        phone: '177****4412',
        registerAt: df(Date.now() - 86400000 * 2000),
        vip: '0',
        kyc: '1',
        lastLogin: df(Date.now() - 86400000 * 90),
        lastIp: '192.168.*.*',
        status: 'SLEEP',
      },
      {
        userCode: 'U204886',
        nickname: 'C2C_小铺',
        phone: '199****2233',
        registerAt: df(Date.now() - 86400000 * 600),
        vip: '1',
        kyc: '1',
        lastLogin: df(Date.now() - 7200000),
        lastIp: '112.64.*.*',
        status: 'OK',
      },
      {
        userCode: 'U204887',
        nickname: '机构子账户01',
        phone: '—',
        registerAt: df(Date.now() - 86400000 * 15),
        vip: '0',
        kyc: '2',
        lastLogin: df(Date.now() - 600000),
        lastIp: '10.8.*.*',
        status: 'OK',
      },
      {
        userCode: 'U204888',
        nickname: '新用户_9281',
        phone: '136****9281',
        registerAt: df(Date.now() - 3600000),
        vip: '0',
        kyc: '0',
        lastLogin: df(Date.now() - 1800000),
        lastIp: '117.136.*.*',
        status: 'OK',
      },
      {
        userCode: 'U204889',
        nickname: 'RiskFlag',
        phone: '150****0007',
        registerAt: df(Date.now() - 86400000 * 60),
        vip: '0',
        kyc: '1',
        lastLogin: df(Date.now() - 86400000 * 2),
        lastIp: '185.220.*.*',
        status: 'BAN',
      },
      {
        userCode: 'U204890',
        nickname: 'AsiaDesk',
        phone: '852****0091',
        registerAt: df(Date.now() - 86400000 * 700),
        vip: '2',
        kyc: '2',
        lastLogin: df(Date.now() - 45000),
        lastIp: '43.154.*.*',
        status: 'OK',
      },
    ],
  },
  contacts: {
    title: '用户通讯录',
    subtitle:
      '链上提现地址簿、白名单校验状态与备注；用于排障与异常出金核对。对接示例：GET /v1/admin/users/contacts。',
    keywordPlaceholder: '用户 / 网络 / 地址片段',
    filterKeywordLabel: '检索',
    listCaption: '通讯录条目',
    drawerNote: '可展示地址创建来源、校验交易哈希、与用户历史出金单的匹配关系。',
    stats: [
      { label: '已验地址', value: '28,102', tone: 'ok' },
      { label: '未验地址', value: '3,401', tone: 'warn' },
      { label: '今日新增', value: '+84', tone: 'default' },
      { label: '多签/合约', value: '126', tone: 'muted' },
    ],
    columns: [
      { prop: 'userCode', label: '用户', width: 112 },
      { prop: 'label', label: '备注名', minWidth: 120 },
      { prop: 'network', label: '网络', width: 100 },
      { prop: 'address', label: '地址(缩略)', minWidth: 200, mono: true },
      { prop: 'verified', label: '校验', width: 88, display: 'tag', tagMap: VERIFIED_MAP },
      { prop: 'addedAt', label: '添加时间', minWidth: 160, display: 'date' },
    ],
    rows: [
      {
        userCode: 'U551002',
        label: '冷钱包 A',
        network: 'TRC20',
        address: 'TXYZabcd…9a2f',
        verified: '1',
        addedAt: df(Date.now() - 86400000 * 200),
      },
      {
        userCode: 'U551002',
        label: '运营热钱包',
        network: 'ERC20',
        address: '0x71a2b3…4c8e',
        verified: '0',
        addedAt: df(Date.now() - 86400000 * 30),
      },
      {
        userCode: 'U204881',
        label: '主站提币',
        network: 'BEP20',
        address: '0x9f1c…22ab',
        verified: '1',
        addedAt: df(Date.now() - 86400000 * 5),
      },
      {
        userCode: 'U204884',
        label: 'Arb 主网',
        network: 'Arbitrum',
        address: '0x4ee0…91cd',
        verified: '1',
        addedAt: df(Date.now() - 86400000 * 12),
      },
      {
        userCode: 'U332211',
        label: 'BTC 储蓄',
        network: 'BTC',
        address: 'bc1qxy2…kp5s',
        verified: '0',
        addedAt: df(Date.now() - 7200000),
      },
      {
        userCode: 'U900001',
        label: '对公结算',
        network: 'TRC20',
        address: 'TLa2f…88ee',
        verified: '1',
        addedAt: df(Date.now() - 86400000 * 400),
      },
      {
        userCode: 'U100008',
        label: '测试地址（勿转）',
        network: 'Sepolia',
        address: '0xdead…beef',
        verified: '0',
        addedAt: df(Date.now() - 86400000),
      },
      {
        userCode: 'U778899',
        label: 'Polygon',
        network: 'Polygon',
        address: '0x55d3…01fa',
        verified: '1',
        addedAt: df(Date.now() - 86400000 * 60),
      },
    ],
  },
}
