package com.exchange.common.exception;

import lombok.Getter;
import lombok.RequiredArgsConstructor;

/**
 * 业务错误码（主干）。按域分段扩展，与数据库/文档统一维护。
 */
@Getter
@RequiredArgsConstructor
public enum ErrorCode {

  OK("OK", "success"),

  AUTH_TOKEN_MISSING("AUTH_TOKEN_MISSING", "未登录或令牌缺失"),
  AUTH_TOKEN_EXPIRED("AUTH_TOKEN_EXPIRED", "登录已过期"),
  AUTH_TOKEN_INVALID("AUTH_TOKEN_INVALID", "令牌无效"),
  AUTH_CREDENTIALS_INVALID("AUTH_CREDENTIALS_INVALID", "账号或密码错误"),
  AUTH_FORBIDDEN("AUTH_FORBIDDEN", "无权限访问"),

  USER_NOT_FOUND("USER_NOT_FOUND", "用户不存在"),
  USER_EMAIL_EXISTS("USER_EMAIL_EXISTS", "邮箱已注册"),

  SYS_PARAM_INVALID("SYS_PARAM_INVALID", "参数错误"),
  SYS_INTERNAL_ERROR("SYS_INTERNAL_ERROR", "系统繁忙，请稍后重试"),

  SPOT_PAIR_NOT_FOUND("SPOT_PAIR_NOT_FOUND", "交易对不存在"),
  SPOT_PAIR_DISABLED("SPOT_PAIR_DISABLED", "交易对未开放"),
  SPOT_ORDER_NOT_FOUND("SPOT_ORDER_NOT_FOUND", "订单不存在"),
  SPOT_ORDER_INVALID_STATE("SPOT_ORDER_INVALID_STATE", "订单状态不允许此操作"),
  SPOT_ORDER_VALIDATION("SPOT_ORDER_VALIDATION", "订单参数校验失败"),
  SPOT_INSUFFICIENT_BALANCE("SPOT_INSUFFICIENT_BALANCE", "可用余额不足"),
  SPOT_DUPLICATE_CLIENT_ORDER("SPOT_DUPLICATE_CLIENT_ORDER", "重复的客户端订单号"),

  CONTRACT_SYMBOL_NOT_FOUND("CONTRACT_SYMBOL_NOT_FOUND", "合约标的不存在"),
  CONTRACT_SYMBOL_DISABLED("CONTRACT_SYMBOL_DISABLED", "合约未开放交易"),
  CONTRACT_VALIDATION("CONTRACT_VALIDATION", "合约参数校验失败"),
  CONTRACT_INSUFFICIENT_MARGIN("CONTRACT_INSUFFICIENT_MARGIN", "保证金不足"),
  CONTRACT_ORDER_NOT_FOUND("CONTRACT_ORDER_NOT_FOUND", "委托不存在"),
  CONTRACT_ORDER_INVALID_STATE("CONTRACT_ORDER_INVALID_STATE", "委托状态不允许此操作"),
  CONTRACT_DUPLICATE_CLIENT_ORDER("CONTRACT_DUPLICATE_CLIENT_ORDER", "重复的客户端订单号"),
  CONTRACT_POSITION_NOT_FOUND("CONTRACT_POSITION_NOT_FOUND", "持仓不存在"),
  CONTRACT_POSITION_QTY_EXCEEDED("CONTRACT_POSITION_QTY_EXCEEDED", "平仓数量超过持仓"),
  CONTRACT_LEVERAGE_INVALID("CONTRACT_LEVERAGE_INVALID", "杠杆倍数不合法"),
  CONTRACT_MARGIN_MODE_SWITCH_DENIED("CONTRACT_MARGIN_MODE_SWITCH_DENIED", "存在持仓时暂不可切换保证金模式"),
  ;

  private final String code;
  private final String defaultMessage;
}
