import type { UserCenterPayload } from '@/types/userCenter'

export function getUserCenterDomainMock(): UserCenterPayload {
  return {
    account: {
      uid: '88291034',
      registeredAt: new Date(Date.now() - 86400_000 * 420).toISOString(),
      accountTier: 'STANDARD',
      accountTierLabel: '标准',
      securityLevel: 'MEDIUM',
      securityScore: 65,
      lastLoginAt: new Date(Date.now() - 1800_000).toISOString(),
      lastLoginIp: '203.0.113.42',
    },
    overview: {
      emailBound: true,
      emailMasked: 'u***@domain.com',
      phoneBound: false,
      phoneMasked: null,
      kycStatus: 'NONE',
      kycTier: 0,
      securityTips: [
        '建议开启 Google 验证器以提高账户安全。',
        '未绑定手机可能影响提现与找回流程。',
        '请勿向任何人泄露验证码与密码。',
      ],
    },
    securityItems: [
      {
        id: 'fund_password',
        title: '资金密码',
        description: '用于提现、C2C 卖出等资金操作时的二次确认',
        status: 'OFF',
        statusLabel: '未设置',
        actionLabel: '设置',
      },
      {
        id: 'password',
        title: '登录密码',
        description: '用于登录与敏感操作验证',
        status: 'ON',
        statusLabel: '已设置',
        actionLabel: '修改',
      },
      {
        id: 'email',
        title: '邮箱',
        description: '用于登录与通知',
        status: 'ON',
        statusLabel: '已绑定',
        actionLabel: '更换',
      },
      {
        id: 'phone',
        title: '手机',
        description: '用于登录验证与短信通知',
        status: 'OFF',
        statusLabel: '未绑定',
        actionLabel: '绑定',
        reserved: true,
      },
      {
        id: 'ga',
        title: 'Google 验证器',
        description: 'TOTP 二次验证',
        status: 'OFF',
        statusLabel: '未开启',
        actionLabel: '开启',
        reserved: true,
      },
      {
        id: 'withdraw_whitelist',
        title: '提现地址白名单',
        description: '仅允许向白名单地址提现',
        status: 'OFF',
        statusLabel: '未开启',
        actionLabel: '管理',
        reserved: true,
      },
      {
        id: 'devices',
        title: '设备管理',
        description: '查看与管理已登录设备',
        status: 'PARTIAL',
        statusLabel: '3 台设备',
        actionLabel: '查看',
        reserved: true,
      },
    ],
    loginRecords: [
      {
        id: '1',
        time: new Date(Date.now() - 1800_000).toISOString(),
        ip: '203.0.113.42',
        device: 'Chrome 131 · macOS',
        location: '中国香港（预留）',
        success: true,
      },
      {
        id: '2',
        time: new Date(Date.now() - 86400_000).toISOString(),
        ip: '198.51.100.8',
        device: 'Mobile Safari · iOS',
        location: null,
        success: true,
      },
      {
        id: '3',
        time: new Date(Date.now() - 86400_000 * 3).toISOString(),
        ip: '192.0.2.1',
        device: 'Firefox · Windows',
        location: '新加坡（预留）',
        success: true,
      },
    ],
  }
}
